
export const children = [{
    id: '1',
    name: 'Giyana',
    type: 'giyana',
    age: 13,
    favoriteFood: 'tacos',
    image: './assets/giyana.png',
    hobbies: ['make jewelry', 'act in drama club', 'hang with friends'],
    bottom: '-150px',
    left: '50%',
},
{
    id: '2',
    name: 'Jaxson',
    type: 'jaxson',
    age: 10,
    favoriteFood: 'lasagna',
    image: './assets/jaxson.png',
    hobbies: ['play video games', 'all things basketball', 'swim'],
    bottom: '0px',
    left: '38%',
},
{
    id: '3',
    name: 'Malakai',
    type: 'malakai',
    age: 6,
    favoriteFood: 'mac and cheese',
    image: './assets/malakai.png',
    hobbies: ['do art projects', 'perform science experiments', 'play outside'],
    bottom: '-200px',
    left: '65%',


},
{
    id: '4',
    name: 'Redd',
    type: 'redd',
    age: 1.5,
    favoriteFood: 'bully treats',
    image: './assets/redd.png',
    hobbies: ['play fetch', 'go for walks', 'find things in the trash'],
    bottom: '-100px',
    left: '5%',
},
];